# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{smartimage}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tony Arcieri"]
  s.date = %q{2010-03-30}
  s.description = %q{    SmartImage provides a cross-platform solution for image compositing that works on both MRI and JRuby.
    If using RMagick feels like swatting a fly with a nucler missile, and ImageScience just doesn't get 
    you there, SmartImage is hopefully at that sweet spot in the middle
}
  s.email = %q{tony@medioh.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/smart_image.rb",
     "lib/smart_image/base_canvas.rb",
     "lib/smart_image/java_canvas.rb",
     "lib/smart_image/ratio_calculator.rb",
     "lib/smart_image/rmagick_canvas.rb",
     "lib/smartimage.rb",
     "smartimage-java.gemspec",
     "smartimage.gemspec",
     "spec/fixtures/mask.png",
     "spec/fixtures/mongoose.jpg",
     "spec/smart_image_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/tmp/.gitignore"
  ]
  s.homepage = %q{http://github.com/tarcieri/smartimage}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{It's like a Swiss Army Knife for images, but one of those tiny ones you can keep on your keychain}
  s.test_files = [
    "spec/smart_image_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<imagesize>, [">= 0.1.1"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<imagesize>, [">= 0.1.1"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<imagesize>, [">= 0.1.1"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
  s.platform = %q{java}
end